apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: validator
  name: validator
spec:
  replicas: 1
  selector:
    matchLabels:
      run: validator
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: validator
    spec:
      containers:
      - image: rcanderson23/validator:v0.0.1-04
        name: validator
        args:
        - --config-file=/config/config.yaml
        ports:
          - containerPort: 8443
            name: https
        volumeMounts:
          - mountPath: /pki
            name: pki
          - mountPath: /config
            name: config
        resources: {}
      volumes:
        - name: pki
          secret:
            secretName: validator-tls
        - name: config
          configMap:
            name: validator-config
status: {}
