apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: validator
  name: validator
  namespace: kube-system
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 8433
  selector:
    run: validator
status:
  loadBalancer: {}
