apiVersion: v1
kind: Service
metadata:
  labels:
    run: validator
  name: validator
  namespace: default
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 8443
  selector:
    run: validator
  sessionAffinity: None
  type: ClusterIP
