apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: validator-webhook
webhooks:
  - name: validator-webhook.carsonanderson.net
    clientConfig:
      service:
        name: validator
        namespace: kube-system
        path: "/validate"
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN0RENDQVp3Q0NRQ1BNOGpGS3NUcmFEQU5CZ2txaGtpRzl3MEJBUXNGQURBY01Sb3dHQVlEVlFRRERCRlcKWVd4cFpHRjBiM0lnVjJWaWFHOXZhekFlRncweE9URXlNall4TWpRM05ERmFGdzB5TURBeE1qVXhNalEzTkRGYQpNQnd4R2pBWUJnTlZCQU1NRVZaaGJHbGtZWFJ2Y2lCWFpXSm9iMjlyTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGCkFBT0NBUThBTUlJQkNnS0NBUUVBbmtCT1B0MUtUVTNXNXlLS2dLbytqYzZVWFdOM1hIaUhhSEhMRmVPM2xxZmUKUmZzWW1XQ05RbWlzNm1wWHhuSklJeEVadFRtKzQ2UDNCVU0yNWE1SFpIYXcraGgxTjJwbHZ3Smw4dHJ1YXBVZApEVjU1TXBCVzdpVW9qNWcwMVNLU0RReURvdkRGUlFFUExLRlJxNElzdHgwS3plVFhwZVBGR1pUTUJrK1diS3UzCmhCaTFOWHozNko5M2IzQXZXMXpBeURQTVEzNVFjVHFQZXVwZXY5WWFwb29CSWYvZ2VvQllnM01ON0FZYjBHMWsKVytTSGUxNHhhR25hbDVIZ2IzaHg4a21xUlFuR3RnUUlxS0F4cGxoYjVMUkJONU1xaE1NdzBJSHlzaGxReVVJYgpYc2FVb21uZjEraDhDUWd3bUpDWUdhUU1DY1cxTUQzYjhRTjdxcWExTVFJREFRQUJNQTBHQ1NxR1NJYjNEUUVCCkN3VUFBNElCQVFCNWNXc2ZrMU5VTXJRNnA4NFNMbHd5dERCTVc3QUJzbmVkWC9wNFo0KzRTNVp6SmFGTS8rdVAKeEE4TWduN0hwWUVIZUVxRnczQjNQOEMxa3N5dUlNTDBBbHpEM2JXall3dCs5MUU0bTB0L2xNcnFEOVlJcEhPcwpJWlF5dXZwZUt2dkE3SDZvS2JCVStvVnpoK29WRk9WNk0zZjU1d1RqS08wcTY5L2Jxa0JWcThIdm9HYmRsUm5vCjBYSm51SEUrcWtpTTFPL1dCcFdtRGNnaVlYam9QR3M4ejRndXYwSk5tdGNTV2xKYVdMc0dTRXFzaEZCUFBTVmkKbGxWdHprWlUrWVFSOEIvZG5SSTBVZzVRbVNqRHhFS2NLV1pWcGNEazFmcGdCZWFSSUZCdkVZZVE2MGs0VjJDaQp3ZnRVYmNxd0V6OTR0UW5xTS9oVVhQY0lxOEo2TTFxUQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    rules:
      - operations: [ "CREATE" ]
        apiGroups: ["apps", ""]
        apiVersions: ["v1"]
        resources: ["pods"]
    namespaceSelector:
      matchLabels:
        validator: enabled

