apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: validator-webhook
webhooks:
  - name: validator-webhook.carsonanderson.net
    clientConfig:
      service:
        name: validator
        namespace: default
        path: "/validate"
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN0RENDQVp3Q0NRRFllNy8zWEF6SHBUQU5CZ2txaGtpRzl3MEJBUXNGQURBY01Sb3dHQVlEVlFRRERCRlcKWVd4cFpHRjBiM0lnVjJWaWFHOXZhekFlRncweE9URXlNall3TlRFM016aGFGdzB5TURBeE1qVXdOVEUzTXpoYQpNQnd4R2pBWUJnTlZCQU1NRVZaaGJHbGtZWFJ2Y2lCWFpXSm9iMjlyTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGCkFBT0NBUThBTUlJQkNnS0NBUUVBMDd3UFFNTnF4UGFEWVNTZ3NZNmVqb3JBZm1uS0UwNkx3NUoyWlNBeVI5eWEKQzFGUzM3RnN6NWF2bHNyT0cvc2ppZVc3Nzlvck5NTTFLMkh0WWJodEVnZ0Z4eUxhTnJvSkYxTldDL1pyanB0WQpFelF4RzRWZHZZWnJtZmkyQ2I2czBoSTFGY2U2NGd1eEJURWFLYmNoYW1GUHcwU1lMMC9xa2M3Wlk4Y29pTEF5CnQweHp5ZHVPcS9VR3lGQlBITHlURGZCR1BzVmtWaXFKZXpuNzhCT25zSWVFSlY4S1dLM25sZkFvSDYxNHM1RS8KcCtwbGh6NEpWZkVMOHRseUhnVnRsZGhpUHlyNWVWU1dpUGhoektlOVFlemJhdERlajVBQVZDL3JQOUxzaU42cAp5dWFKM1BhY1lTWkRPKzJFOGNsVkVXY0l0Q242WjdXY1YrNTNVOU9IM1FJREFRQUJNQTBHQ1NxR1NJYjNEUUVCCkN3VUFBNElCQVFDZVB6ZHRYMEUybTRpSTlGdlBSQjFaTmZkc1ZOM2dLM01KY1FmTCt4UTdKVjRvMS9kSEtDaTgKRVBwbDFsRldBMTZtelJnZ2dZQTErbHlQZVdCUmNNeEgrRDhWbGhyWVl5MlZyQ3JtdzBaUzRwbFVDdENJMjUrUApkK1BmaENUS0U1Qm9ZTExaVU1lQlR2SWdpQ04vTDhJeDRPdENuVThRallvSWtDOWJLclVWVjl6S0VzWHl4cjZTCllqYjRUTjVQdkJnTUlSbXVtTUNlTE1LVGpxajBNYktMalBwRjY5VmtFdVF3TVJRWjJVa2I0YnlsMERONi9oVkgKYnRpUElQWlhVbzlFUVhPbzd6bDRpMU9PaDZRWVVPYkhwKytGa05vcXIzSUpiaVdjRlphYWRFRTNIc1BTeXFzbApzSStncGVob0x4TkQ2WGE1LzRQUkVBQjBCTW0xYWE1YQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    rules:
      - operations: [ "CREATE", "UPDATE" ]
        apiGroups: ["apps", ""]
        apiVersions: ["v1"]
        resources: ["pods","services"]
    namespaceSelector:
      matchLabels:
        validator: enabled

